### PR TITLE
Migrate to sdkman (was gvm)

### LINKED ISSUE #13: gvmtool fails to install during Vagrant provisioning
The provisioning script attempts to install gvmtool from a URL, which now redirects to sdkman, a newer and rebranded gvmtool. This causes gvmtool installation to silently fail, and later causes marketplace.war build failure (since grails never gets installed).

Relevant log entries:
```
==> ozp-centos6.6: /vagrant/initial_provisioning.sh: line 22: /home/vagrant/.gvm/bin/gvm-init.sh: No such file or directory
==> ozp-centos6.6: /vagrant/initial_provisioning.sh: line 30: /home/vagrant/.gvm/etc/config: No such file or directory
==> ozp-centos6.6: /vagrant/initial_provisioning.sh: line 33: gvm: command not found
==> ozp-centos6.6: /vagrant/initial_provisioning.sh: line 34: gvm: command not found
==> ozp-centos6.6: /vagrant/initial_provisioning.sh: line 35: gvm: command not found
...
==> ozp-centos6.6: /vagrant/build.sh: line 17: /home/vagrant/.gvm/bin/gvm-init.sh: No such file or directory
==> ozp-centos6.6: /vagrant/build.sh: line 18: gvm: command not found
==> ozp-centos6.6: /vagrant/build.sh: line 19: gvm: command not found
...
==> ozp-centos6.6: cp: 
==> ozp-centos6.6: cannot stat `ozp-rest/target/marketplace.war'
==> ozp-centos6.6: : No such file or directory
...
==> ozp-centos6.6: mv: 
==> ozp-centos6.6: cannot stat `marketplace.war'
==> ozp-centos6.6: : No such file or directory
==> ozp-centos6.6: chown: 
==> ozp-centos6.6: cannot access `/var/lib/tomcat/webapps/marketplace.war'
==> ozp-centos6.6: : No such file or directory
...
==> ozp-centos6.6: {"error":"IndexMissingException[[marketplace] missing]","status":404}
```

I believe this is the root cause for issue #12.

### PR DESCRIPTION
**Pull request by jkins**
Just update to sdkman. This should fix #13.

### CODE REVIEW

**Comment by tonyalletag** [comment]
@jkins thaks for the pull request. I just noticed this! wish I would have saw it earlier.

**Comment by jkins** [comment]
No problem. :)

**Comment by arw180** [comment]
:+1: looks good, thanks for the contribution!

**Comment by tonyalletag** [comment]
:+1:

**Pull request merged**
